language: c
sudo: required
install: 
  - wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh  
script: 
  - bash -ex .travis-opam.sh
env:
  global:
   - PINS="distributed:. distributed-lwt:. lwt"   
  matrix:
    - OCAML_VERSION=4.02 INSTALL=false PACKAGE=distributed-lwt POST_INSTALL_HOOK="bash -ex ./coverage.sh"
    - OCAML_VERSION=4.03 INSTALL=false PACKAGE=distributed-lwt POST_INSTALL_HOOK="bash -ex ./coverage.sh"
    - OCAML_VERSION=4.04 INSTALL=false PACKAGE=distributed-lwt POST_INSTALL_HOOK="bash -ex ./coverage.sh"     
    - OCAML_VERSION=4.05 INSTALL=false PACKAGE=distributed-lwt POST_INSTALL_HOOK="bash -ex ./coverage.sh"    
    - OCAML_VERSION=4.06 INSTALL=false PACKAGE=distributed-lwt POST_INSTALL_HOOK="bash -ex ./coverage.sh"
    - OCAML_VERSION=4.07 INSTALL=false PACKAGE=distributed-lwt POST_INSTALL_HOOK="bash -ex ./coverage.sh"
    - OCAML_VERSION=4.08 INSTALL=false PACKAGE=distributed-lwt POST_INSTALL_HOOK="bash -ex ./coverage.sh"
    - OCAML_VERSION=4.09 INSTALL=false PACKAGE=distributed-lwt POST_INSTALL_HOOK="bash -ex ./coverage.sh" 
os:
  - linux
  - osx
