language: c
sudo: required
install: 
  - wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh  
script: 
  - bash -ex .travis-opam.sh
env:
  global:
   - PINS="distributed:. distributed-lwt:. lwt"   
  matrix:
    - OCAML_VERSION=4.02 PACKAGE=distributed-lwt POST_INSTALL_HOOK="bash -ex ./coverage.sh"
    - OCAML_VERSION=4.03 PACKAGE=distributed-lwt POST_INSTALL_HOOK="bash -ex ./coverage.sh"
    - OCAML_VERSION=4.04 PACKAGE=distributed-lwt POST_INSTALL_HOOK="bash -ex ./coverage.sh"     
    - OCAML_VERSION=4.05 PACKAGE=distributed-lwt POST_INSTALL_HOOK="bash -ex ./coverage.sh"    
    - OCAML_VERSION=4.06 PACKAGE=distributed-lwt POST_INSTALL_HOOK="bash -ex ./coverage.sh"
    - OCAML_VERSION=4.07 PACKAGE=distributed-lwt POST_INSTALL_HOOK="bash -ex ./coverage.sh"
    - OCAML_VERSION=4.08 PACKAGE=distributed-lwt POST_INSTALL_HOOK="bash -ex ./coverage.sh"
    - OCAML_VERSION=4.09 PACKAGE=distributed-lwt POST_INSTALL_HOOK="bash -ex ./coverage.sh" 
os:
  - linux
  - osx
