platform:
  - x64

image: Visual Studio 2015

environment:
  CYG_ROOT: cygwin64
  CYG_ARCH: x86_64
  CYG_CACHE: C:/cygwin/var/cache/setup
  CYG_MIRROR: http://mirrors.kernel.org/sourceware/cygwin/  
  
  matrix:
    - OCAML_BRANCH: 4.02.3
    - OCAML_BRANCH: 4.03.0
    - OCAML_BRANCH: 4.04.0
    - OCAML_BRANCH: 4.05.0
    - OCAML_BRANCH: 4.06.1
    - OCAML_BRANCH: 4.07.1
    - OCAML_BRANCH: 4.08.1
    - OCAML_BRANCH: 4.09.0    

build_script:
  - set CYGWIN="nodosfilewarning winsymlinks:native"
  - C:\cygwin64\setup-x86_64.exe --root=C:\cygwin64 --quiet-mode --no-desktop --no-startmenu --packages=perl,diffutils,rsync,git,unzip,gzip,tar,make,mingw64-i686-gcc-core,mingw64-x86_64-gcc-core,m4,patch
  - appveyor DownloadFile "https://github.com/fdopen/opam-repository-mingw/releases/download/0.0.0.1/opam64.tar.xz" -FileName "C:\projects\opam64.tar.xz" 
  - C:\cygwin64\bin\bash.exe -lc "$APPVEYOR_BUILD_FOLDER/appveyor.sh"  
  
